version: "3.7"
services:
  extension_payments:
    build: .
    user: "node"
    environment:
      - NODE_ENV=production
      - APISUITE_EXT_PAYMENTS_PUBLIC_URL
      - APISUITE_EXT_PAYMENTS_RME_URL
      - APISUITE_EXT_PAYMENTS_STRIPE_SECRET_KEY
      - APISUITE_EXT_PAYMENTS_STRIPE_MODE
    ports:
      - ${APISUITE_EXT_PAYMENTS_PORT:-3003}:3003
    volumes:
      - ./:/home/node/app
      - ${INTERCEPTOR_CONFIG_PATH:-./interceptor.config.json}:/home/node/app/interceptor.config.json
networks:
  default:
    external:
      name: apisuitedb-net-${ENV}
